### ISSUE TITLE
A guess on why your README has more forks

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [ouuan/ouuan#1]
Many people use your awesome README as a template for their own introduction!

Well, I don't deny I'm one of these people...

**Comment by ouuan** [comment]
> Many people use your awesome README as a template for their own introduction!

Well, I've certainly thought of this, but:

1. Many of them are not using my README or even don't have a profile README.
2. It doesn't require forking to use my README. I guess many people think it requires forking to clone.
3. If anyone wants to use my README as a template, why not star it?
